version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - ./backend:/app/backend
    depends_on:
      - db
    environment:
      DB_NAME: blog
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "5001:5000"
    restart: always

volumes:
  pgdata: